In [1]:
import numpy as np

def is_diagonally_dominant(matrix):
    """
    Takes a square matrix (list of lists or numpy array) and returns 
    True if it is diagonally dominant, False otherwise.
    """
    mat = np.array(matrix)
    n = mat.shape[0]
    
    for i in range(n):
        # Find the absolute value of the diagonal element
        diag_element = np.abs(mat[i, i])
        
        # Calculate the sum of the absolute values of the rest of the row
        # (Sum of the whole row minus the diagonal element)
        row_sum = np.sum(np.abs(mat[i, :])) - diag_element
        
        # If the diagonal element is less than the sum of the others, it fails
        if diag_element < row_sum:
            return False
            
    return True

def test_dominance(matrix):
    """
    Helper function to print the results.
    """
    result = is_diagonally_dominant(matrix)
    print(f"Is the matrix diagonally dominant? {result}")
    print(np.array(matrix))
    print() # Adds a blank line for readability between tests

# --- Test Cases ---

# Test Matrix 1: Diagonally Dominant (True)
matrix_1 = [
    [ 3, -2,  1],
    [ 1, -3,  2],
    [-1,  2,  4]
]
test_dominance(matrix_1)

# Test Matrix 2: Not Diagonally Dominant (False)
# The first row's diagonal (2) is less than the sum of the others (4+5 = 9)
matrix_2 = [
    [ 2,  4,  5],
    [ 1,  8,  2],
    [ 3, -1,  6]
]
test_dominance(matrix_2)

# Test Matrix 3: Strictly Diagonally Dominant (True)
matrix_3 = [
    [ 7,  2,  0],
    [ 3,  5, -1],
    [ 0,  5, -6]
]
test_dominance(matrix_3)

Is the matrix diagonally dominant? True
[[ 3 -2  1]
 [ 1 -3  2]
 [-1  2  4]]

Is the matrix diagonally dominant? False
[[ 2  4  5]
 [ 1  8  2]
 [ 3 -1  6]]

Is the matrix diagonally dominant? True
[[ 7  2  0]
 [ 3  5 -1]
 [ 0  5 -6]]

